### ISSUE TITLE
Setupでエラー

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [uei/deepstation#13]
Setup時にデータベースのエラーが出ます。
$ sqlite3 deepstation.db < ./scheme/deepstation.sql
Error: near line 1: table Model already exists
Error: near line 20: table Dataset already exists

続けて
$ python2.7 main.py
の後に、ブラウザから起動しますが
zipで固めたCaltech 101のデータをDatasetに与えても
解凍されず、正しく設定されていないようです。

どうしたら動作しますでしょうか？

環境：
OS:  CentOS release 6.6

**Comment by hidesuke** [comment]
githubにアップロードしてある deepstation.db にすでにテーブルがセットされているため、上記でエラーが発生しておりますが、問題なく動作すると思います。  
READMEを修正するか、deepstation.db を変更するか検討します。

zipが解凍されない件ですが、ターミナルにエラーなどが表示されていませんでしょうか？　エラーが出ているようでしたら、エラーの内容を教えてください。  
また、考えられることとしては、settings.yamlに指定されているディレクトリのパーミッションが正しく設定されていない可能性があります。main.pyを実行するユーザが読み書き可能な設定になっているかご確認ください。

**Comment by hidesuke** [comment]
セットアップ時のエラーですが、テーブルが既にあった場合は、何もしないような変更を追加しました。

**Comment by Kenichiro-Yoshimi** [comment]
データベースのご対応、ありがとうございました。

zipが解凍されない件、Caltech 101のデータ量が多すぎるようでした。
数フォルダだけにして、zipで固めてアップロードしますと、無事に解凍されました。

ありがとうございました。
