### ISSUE TITLE
compute_meanの計算違い

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [uei/deepstation#18]
main.pyのcompute_meanのl. 644が違っているように見えます。
  644':            sum_image += image
の間違いではないでしょうか？

640:        if sum_image is None:
641:            sum_image = numpy.ndarray(image.shape, dtype=numpy.float32)
642:            sum_image[:] = image
643:        else:
644:            sum_image += 1
645:        count += 1

**Comment by hidesuke** [comment]
ご指摘ありがとうございます。 #19 で修正いたしました。

**Comment by Kenichiro-Yoshimi** [comment]
有難うございました。
